@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "3.5.28";

olcnePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
  containers: [('container-registry.oracle.com/olcne/etcd:' + version) : 'olcne/etcd:' + version],
  yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder'],
  yumOL9Repos: ['ol9_appstream', 'ol9_codeready_builder'],
  platforms: ['ol8', 'ol9'],
  architectures: ['x86_64', 'aarch64'],
)
